---

version: "3.8"


volumes:
  mvn:
  data:

services:

  alpine_builder:
    build:
      dockerfile: container/Dockerfile-alpine
      target: builder
      context: .
      # Remove before flight
      network: host
    image: graalvm-alpine
    environment:
      USER: ${USER:-maven}
    volumes:
      - mvn:/home/${USER:-maven}/.m2
      - .:/project

  alpine_native:
    extends:
      service: alpine_builder
    command: [
      "mvn",
      "-Pnative",
      "clean",
      "package",
    ]

  alpine_native_run_local:
    image: alpine
    init: true
    entrypoint:
      - /project/geoip-server-linux-x86_64
    command:
      - --license-key=${LICENSE_KEY}
    volumes:
      - ./target/:/project
      - data:/tmp
    ports:
      - "18888:18888"

  alpine_native_image:
    build:
      dockerfile: container/Dockerfile-alpine
      target: native
      context: .
    image: geoip-alpine
    init: true
    command:
      - --license-key=${LICENSE_KEY}
      #- --static-data-file=/tmp/geoip-data/current.mmdb
    volumes:
      - data:/tmp
      #- ./data/GeoLite2-Country.mmdb:/tmp/geoip-data/current.mmdb:ro
      #- ./data:/tmp/geoip-data:ro
      #- data:/tmp/geoip-data
    ports:
      - "18888:18888"
